# ===================================================================
# Spring Cloud Config bootstrap configuration for the "prod" profile
# ===================================================================

spring:
  config:
    import:
      - classpath:mysql-local.yml
      - optional:nacos:mysql-local.yml?group=${spring.application.name}
      - classpath:feign-local.yml
      - optional:nacos:feign-local.yml?group=${spring.application.name}
      - classpath:redis-local.yml
      - optional:nacos:redis-local.yml?group=${spring.application.name}

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:192.168.71.1:8848} # 你的nacos地址
      config:
        server-addr: ${NACOS_SERVER:192.168.71.1:8848}
        shared-configs[0]:
          data-id: error-code.yaml
        shared-configs[1]:
          data-id: user-server.yaml
        shared-configs[2]:
          data-id: file-server.yaml
        refreshable-dataids: error-code.yaml
        file-extension: yaml
        group: share

server:
  port: 8081
  servlet:
    context-path: /yun

hcy: #自研日志插件配置，详细请查阅日志插件说明文档
  plugin:
    logger:
      stack:
        maxDepthPerThrowable: 10
        maxLength: 4096

liteflow:
  rule-source: flow.xml